import { create } from "zustand";
import { arrayMove } from "@dnd-kit/sortable";
import type {
  BaseChordDataKey,
  ShapeDataKey,
  UnifiedMusicKeysDataKey,
} from "@/data";
import { getOrderedShapeVariantDataKeys } from "@/components/ShapeMulitStepSliderExplorer/helpers/getOrderedShapeVariantDataKeys";
import { subscribeWithSelector } from "zustand/middleware";

export interface ShapePlayerBrick {
  id: string;
  unifiedMusicKeysDataKey: UnifiedMusicKeysDataKey;
  baseChordDataKey: BaseChordDataKey;
  shapeDataKey: ShapeDataKey;
  semitoneOffsetFromMajorRoot: number;
  playLength: number;
  sliderRange?: [number, number];
}

interface ShapePlayerHistoryEntry {
  shapePlayerBricks: ShapePlayerBrick[];
  type: "SINGLE_REMOVAL" | "CLEAN_ALL";
  originalIndex?: number;
}

interface ShapePlayerState {
  exerciseTitle: string | null;
  shapePlayerBricks: ShapePlayerBrick[];
  shapePlayerHistory: ShapePlayerHistoryEntry[];
  setExerciseTitle: (exerciseTitle: string) => void;
  addShapePlayerBrick: (brickData: Omit<ShapePlayerBrick, "id">) => void;
  removeShapePlayerBrick: (id: string) => void;
  updateBrickRange: (id: string, sliderRange: [number, number]) => void;
  clearShapePlayerBricks: () => void;
  restoreLastAction: () => void;
  reorderShapePlayerBricks: (oldIndex: number, newIndex: number) => void;
  setBricks: (shapePlayerBricks: ShapePlayerBrick[]) => void;
}

export const useShapePlayerStore = create<ShapePlayerState>()(
  subscribeWithSelector((set) => {
    const getUpdatedTitle = (
      bricks: ShapePlayerBrick[],
      currentTitle: string | null,
    ) => {
      if (bricks.length === 0) return null;

      const firstBrick = bricks[0];
      const musicKey = firstBrick.unifiedMusicKeysDataKey;
      const defaultGenerated = `Exercise in Key of ${musicKey}`;
      const isAutoGenerated =
        currentTitle === null || currentTitle.startsWith("Exercise in Key of");

      return isAutoGenerated ? defaultGenerated : currentTitle;
    };

    return {
      exerciseTitle: null,
      shapePlayerBricks: [],
      shapePlayerHistory: [],

      setExerciseTitle: (exerciseTitle) => set({ exerciseTitle }),

      addShapePlayerBrick: (brickData) => {
        const locations = getOrderedShapeVariantDataKeys({
          shapeDataKey: brickData.shapeDataKey,
          unifiedMusicKeysDataKey: brickData.unifiedMusicKeysDataKey,
          semitoneOffsetFromMajorRoot: brickData.semitoneOffsetFromMajorRoot,
        });

        const maxLocationIndex = Math.max(0, locations.length - 1);
        const defaultRange: [number, number] = [0, maxLocationIndex];

        const newBrick: ShapePlayerBrick = {
          ...brickData,
          id: crypto.randomUUID(),
          sliderRange: brickData.sliderRange ?? defaultRange,
        };

        set((state) => {
          const newBricks = [...state.shapePlayerBricks, newBrick];
          return {
            shapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            shapePlayerHistory: [],
          };
        });
      },

      removeShapePlayerBrick: (idToRemove) => {
        set((state) => {
          const brickIndex = state.shapePlayerBricks.findIndex(
            (shapePlayerBrick) => shapePlayerBrick.id === idToRemove,
          );

          if (brickIndex === -1) return state;

          const updatedBricks = state.shapePlayerBricks.filter(
            (shapePlayerBrick) => shapePlayerBrick.id !== idToRemove,
          );

          return {
            shapePlayerBricks: updatedBricks,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
            shapePlayerHistory: [
              ...state.shapePlayerHistory,
              {
                shapePlayerBricks: [state.shapePlayerBricks[brickIndex]],
                type: "SINGLE_REMOVAL",
                originalIndex: brickIndex,
              },
            ],
          };
        });
      },

      clearShapePlayerBricks: () => {
        set((state) => {
          if (state.shapePlayerBricks.length === 0) return state;

          return {
            shapePlayerBricks: [],
            exerciseTitle: null,
            shapePlayerHistory: [
              ...state.shapePlayerHistory,
              {
                shapePlayerBricks: [...state.shapePlayerBricks],
                type: "CLEAN_ALL",
              },
            ],
          };
        });
      },

      restoreLastAction: () => {
        set((state) => {
          const lastEntry = state.shapePlayerHistory.at(-1);
          if (!lastEntry) return state;

          const remainingHistory = state.shapePlayerHistory.slice(0, -1);
          let newBricks = [...state.shapePlayerBricks];

          if (lastEntry.type === "CLEAN_ALL") {
            newBricks = lastEntry.shapePlayerBricks;
          } else {
            const [restoredBrick] = lastEntry.shapePlayerBricks;
            const insertionIndex = lastEntry.originalIndex ?? 0;
            newBricks.splice(insertionIndex, 0, restoredBrick);
          }

          return {
            shapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            shapePlayerHistory: remainingHistory,
          };
        });
      },

      reorderShapePlayerBricks: (oldIndex, newIndex) => {
        set((state) => {
          const updatedBricks = arrayMove(
            state.shapePlayerBricks,
            oldIndex,
            newIndex,
          );
          return {
            shapePlayerBricks: updatedBricks,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
          };
        });
      },

      setBricks: (shapePlayerBricks) =>
        set((state) => ({
          shapePlayerBricks,
          exerciseTitle: getUpdatedTitle(
            shapePlayerBricks,
            state.exerciseTitle,
          ),
        })),

      updateBrickRange: (id, sliderRange) => {
        set((state) => ({
          shapePlayerBricks: state.shapePlayerBricks.map((shapePlayerBrick) =>
            shapePlayerBrick.id === id
              ? { ...shapePlayerBrick, sliderRange }
              : shapePlayerBrick,
          ),
        }));
      },
    };
  }),
);
