import { create } from "zustand";
import { arrayMove } from "@dnd-kit/sortable";
import { getOrderedShapeVariantDataKeys } from "@/components/ShapeExplorer/helpers/getOrderedShapeVariantDataKeys";
import { subscribeWithSelector } from "zustand/middleware";
import type { ShapePlayerBrick, ShapePlayerState } from "./types";

export const useShapePlayerStore = create<ShapePlayerState>()(
  subscribeWithSelector((set) => {
    const getUpdatedTitle = (
      bricks: ShapePlayerBrick[],
      currentTitle: string | null,
    ) => {
      if (bricks.length === 0) return null;

      const firstBrick = bricks[0];
      const musicKey = firstBrick.unifiedMusicKeysDataKey;
      const defaultGenerated = `Exercise in Key of ${musicKey}`;
      const isAutoGenerated =
        currentTitle === null || currentTitle.startsWith("Exercise in Key of");

      return isAutoGenerated ? defaultGenerated : currentTitle;
    };

    return {
      exerciseTitle: null,
      guitarShapePlayerBricks: [],
      guitarShapePlayerHistory: [],

      setExerciseTitle: (exerciseTitle) => set({ exerciseTitle }),

      addShapePlayerBrick: (brickData) => {
        const locations = getOrderedShapeVariantDataKeys({
          guitarShapeDataKey: brickData.guitarShapeDataKey,
          unifiedMusicKeysDataKey: brickData.unifiedMusicKeysDataKey,
          semitoneOffsetFromMajorRoot: brickData.semitoneOffsetFromMajorRoot,
        });

        const maxLocationIndex = Math.max(0, locations.length - 1);
        const defaultRange: [number, number] = [0, maxLocationIndex];

        const newBrick: ShapePlayerBrick = {
          ...brickData,
          id: crypto.randomUUID(),
          sliderRange: brickData.sliderRange ?? defaultRange,
          targetSharpNoteNames: brickData.targetSharpNoteNames ?? [],
        };

        set((state) => {
          const newBricks = [...state.guitarShapePlayerBricks, newBrick];
          return {
            guitarShapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            guitarShapePlayerHistory: [],
          };
        });
      },

      updateBrick: (id, partialBrick) => {
        set((state) => ({
          guitarShapePlayerBricks: state.guitarShapePlayerBricks.map((brick) =>
            brick.id === id ? { ...brick, ...partialBrick } : brick,
          ),
        }));
      },

      removeShapePlayerBrick: (idToRemove) => {
        set((state) => {
          const brickIndex = state.guitarShapePlayerBricks.findIndex(
            (brick) => brick.id === idToRemove,
          );

          if (brickIndex === -1) return state;

          const updatedBricks = state.guitarShapePlayerBricks.filter(
            (brick) => brick.id !== idToRemove,
          );

          return {
            guitarShapePlayerBricks: updatedBricks,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
            guitarShapePlayerHistory: [
              ...state.guitarShapePlayerHistory,
              {
                guitarShapePlayerBricks: [
                  state.guitarShapePlayerBricks[brickIndex],
                ],
                type: "SINGLE_REMOVAL",
                originalIndex: brickIndex,
              },
            ],
          };
        });
      },

      clearShapePlayerBricks: () => {
        set((state) => {
          if (state.guitarShapePlayerBricks.length === 0) return state;

          return {
            guitarShapePlayerBricks: [],
            exerciseTitle: null,
            guitarShapePlayerHistory: [
              ...state.guitarShapePlayerHistory,
              {
                guitarShapePlayerBricks: [...state.guitarShapePlayerBricks],
                type: "CLEAN_ALL",
              },
            ],
          };
        });
      },

      restoreLastAction: () => {
        set((state) => {
          const lastEntry = state.guitarShapePlayerHistory.at(-1);
          if (!lastEntry) return state;

          const remainingHistory = state.guitarShapePlayerHistory.slice(0, -1);
          let newBricks = [...state.guitarShapePlayerBricks];

          if (lastEntry.type === "CLEAN_ALL") {
            newBricks = lastEntry.guitarShapePlayerBricks;
          } else {
            const [restoredBrick] = lastEntry.guitarShapePlayerBricks;
            const insertionIndex = lastEntry.originalIndex ?? 0;
            newBricks.splice(insertionIndex, 0, restoredBrick);
          }

          return {
            guitarShapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            guitarShapePlayerHistory: remainingHistory,
          };
        });
      },

      reorderShapePlayerBricks: (oldIndex, newIndex) => {
        set((state) => {
          const updatedBricks = arrayMove(
            state.guitarShapePlayerBricks,
            oldIndex,
            newIndex,
          );
          return {
            guitarShapePlayerBricks: updatedBricks,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
          };
        });
      },

      setBricks: (guitarShapePlayerBricks) =>
        set((state) => ({
          guitarShapePlayerBricks,
          exerciseTitle: getUpdatedTitle(
            guitarShapePlayerBricks,
            state.exerciseTitle,
          ),
        })),
    };
  }),
);
