import { create } from "zustand";
import { arrayMove } from "@dnd-kit/sortable";
import { getOrderedShapeVariantDataKeys } from "@/components/ShapeExplorer/helpers/getOrderedShapeVariantDataKeys";
import { subscribeWithSelector } from "zustand/middleware";
import { transposeKey } from "./helpers/transposeKey";
import type { ShapePlayerBrick, ShapePlayerState } from "./types";

export const useShapePlayerStore = create<ShapePlayerState>()(
  subscribeWithSelector((set) => {
    const getUpdatedTitle = (
      bricks: ShapePlayerBrick[],
      currentTitle: string | null,
    ) => {
      if (bricks.length === 0) return null;

      const firstBrick = bricks[0];
      const musicKey = firstBrick.unifiedMusicKeysDataKey;
      const defaultGenerated = `Untitled exercise in Key of ${musicKey}`;
      const isAutoGenerated =
        currentTitle === null || currentTitle.startsWith("Exercise in Key of");

      return isAutoGenerated ? defaultGenerated : currentTitle;
    };

    return {
      exerciseTitle: null,
      guitarShapePlayerBricks: [
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord2",
          guitarShapeDataKey: "m_add9",
          semitoneOffsetFromMajorRoot: 2,
          isMajorMode: false,
          playLength: 4,
          id: "fd909615-4447-4761-9c6d-7284946a76c9",
          sliderRange: [4, 4],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord1",
          guitarShapeDataKey: "_6",
          semitoneOffsetFromMajorRoot: 0,
          isMajorMode: false,
          playLength: 4,
          id: "f5d62f2e-b425-4bf7-9397-02b3b400e4ad",
          sliderRange: [4, 4],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord6",
          guitarShapeDataKey: "minor_pent",
          semitoneOffsetFromMajorRoot: 9,
          isMajorMode: false,
          playLength: 4,
          id: "d7d5c192-0850-4def-9517-91a9fbb86ba3",
          sliderRange: [4, 4],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord3Ph",
          guitarShapeDataKey: "dominant",
          semitoneOffsetFromMajorRoot: 4,
          isMajorMode: false,
          playLength: 4,
          id: "d1859e26-dc42-4f5e-bb4c-7a0b826755bf",
          sliderRange: [6, 6],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord4",
          guitarShapeDataKey: "M7",
          semitoneOffsetFromMajorRoot: 5,
          isMajorMode: false,
          playLength: 4,
          id: "7725bbaa-d418-4426-88cd-cc003ec97197",
          sliderRange: [5, 5],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord1",
          guitarShapeDataKey: "M7",
          semitoneOffsetFromMajorRoot: 0,
          isMajorMode: false,
          playLength: 4,
          id: "6368d588-d804-469a-ab00-77bf02282de5",
          sliderRange: [5, 5],
          targetNoteIndices: [1],
        },
        {
          unifiedMusicKeysDataKey: "Db",
          baseChordDataKey: "BaseChord3Ph",
          guitarShapeDataKey: "dominant",
          semitoneOffsetFromMajorRoot: 4,
          isMajorMode: false,
          playLength: 8,
          id: "c22f42a4-f31f-4fc1-b3db-56eebdc5b6a9",
          sliderRange: [6, 6],
          targetNoteIndices: [1],
        },
      ],
      guitarShapePlayerHistory: [],
      activeBrickId: null,
      playbackRange: null,

      setPlaybackRange: (playbackRange) => set({ playbackRange }),

      setExerciseTitle: (exerciseTitle) => set({ exerciseTitle }),

      setActiveBrickId: (activeBrickId) => set({ activeBrickId }),

      addShapePlayerBrick: (brickData) => {
        const locations = getOrderedShapeVariantDataKeys({
          guitarShapeDataKey: brickData.guitarShapeDataKey,
          unifiedMusicKeysDataKey: brickData.unifiedMusicKeysDataKey,
          semitoneOffsetFromMajorRoot: brickData.semitoneOffsetFromMajorRoot,
        });

        const maxLocationIndex = Math.max(0, locations.length - 1);
        const defaultRange: [number, number] = [0, maxLocationIndex];

        const newBrick: ShapePlayerBrick = {
          ...brickData,
          id: crypto.randomUUID(),
          sliderRange: brickData.sliderRange ?? defaultRange,
          targetNoteIndices: brickData.targetNoteIndices ?? [1],
        };

        set((state) => {
          const newBricks = [...state.guitarShapePlayerBricks, newBrick];
          return {
            guitarShapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            guitarShapePlayerHistory: [],
          };
        });
      },

      updateBrick: (id, partialBrick) => {
        set((state) => ({
          guitarShapePlayerBricks: state.guitarShapePlayerBricks.map((brick) =>
            brick.id === id ? { ...brick, ...partialBrick } : brick,
          ),
        }));
      },

      removeShapePlayerBrick: (idToRemove) => {
        set((state) => {
          const brickIndex = state.guitarShapePlayerBricks.findIndex(
            (brick) => brick.id === idToRemove,
          );

          if (brickIndex === -1) return state;

          const updatedBricks = state.guitarShapePlayerBricks.filter(
            (brick) => brick.id !== idToRemove,
          );

          const wasActiveRemoved = state.activeBrickId === idToRemove;

          return {
            guitarShapePlayerBricks: updatedBricks,
            activeBrickId: wasActiveRemoved ? null : state.activeBrickId,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
            guitarShapePlayerHistory: [
              ...state.guitarShapePlayerHistory,
              {
                guitarShapePlayerBricks: [
                  state.guitarShapePlayerBricks[brickIndex],
                ],
                type: "SINGLE_REMOVAL",
                originalIndex: brickIndex,
              },
            ],
          };
        });
      },

      clearShapePlayerBricks: () => {
        set((state) => {
          if (state.guitarShapePlayerBricks.length === 0) return state;

          return {
            guitarShapePlayerBricks: [],
            activeBrickId: null,
            exerciseTitle: null,
            playbackRange: null,
            guitarShapePlayerHistory: [
              ...state.guitarShapePlayerHistory,
              {
                guitarShapePlayerBricks: [...state.guitarShapePlayerBricks],
                type: "CLEAN_ALL",
              },
            ],
          };
        });
      },

      restoreLastAction: () => {
        set((state) => {
          const lastEntry = state.guitarShapePlayerHistory.at(-1);
          if (!lastEntry) return state;

          const remainingHistory = state.guitarShapePlayerHistory.slice(0, -1);
          let newBricks = [...state.guitarShapePlayerBricks];

          if (lastEntry.type === "CLEAN_ALL") {
            newBricks = lastEntry.guitarShapePlayerBricks;
          } else {
            const [restoredBrick] = lastEntry.guitarShapePlayerBricks;
            const insertionIndex = lastEntry.originalIndex ?? 0;
            newBricks.splice(insertionIndex, 0, restoredBrick);
          }

          return {
            guitarShapePlayerBricks: newBricks,
            exerciseTitle: getUpdatedTitle(newBricks, state.exerciseTitle),
            guitarShapePlayerHistory: remainingHistory,
          };
        });
      },

      reorderShapePlayerBricks: (oldIndex, newIndex) => {
        set((state) => {
          const updatedBricks = arrayMove(
            state.guitarShapePlayerBricks,
            oldIndex,
            newIndex,
          );
          return {
            guitarShapePlayerBricks: updatedBricks,
            exerciseTitle: getUpdatedTitle(updatedBricks, state.exerciseTitle),
          };
        });
      },

      setBricks: (guitarShapePlayerBricks) =>
        set((state) => ({
          guitarShapePlayerBricks,
          playbackRange: null,
          exerciseTitle: getUpdatedTitle(
            guitarShapePlayerBricks,
            state.exerciseTitle,
          ),
        })),

      transposeShapePlayerBricks: (semitones) => {
        set((state) => {
          if (state.guitarShapePlayerBricks.length === 0) return state;

          const transposedBricks = state.guitarShapePlayerBricks.map(
            (brick) => ({
              ...brick,
              unifiedMusicKeysDataKey: transposeKey(
                brick.unifiedMusicKeysDataKey,
                semitones,
              ),
            }),
          );

          return {
            guitarShapePlayerBricks: transposedBricks,
            exerciseTitle: getUpdatedTitle(
              transposedBricks,
              state.exerciseTitle,
            ),
          };
        });
      },
    };
  }),
);
